### ISSUE TITLE
github actions overwrites latest image

### ISSUE THREAD

**Issue by peccu** [peccu/emacs-wslg#2]
branch buildenv overwrites latest tag in docker images.

I need to add condition for latest tag pushing,

**Comment by peccu** [comment]
```yaml

name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
```

ref. https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
